

export default Object.freeze({
  NONE: 'FORMATTER_NONE',
  JAVASCRIPT: 'FORMATTER_JAVASCRIPT',
  GRPC: 'FORMATTER_GRPC_SERVICE',
  CAYENNELPP: 'FORMATTER_CAYENNELPP',
  REPOSITORY: 'FORMATTER_REPOSITORY',
  DEFAULT: 'DEFAULT',
})
