
export default Object.freeze({
  DEVICE_ID: 'device-id',
  DEVICE_ADDRESS: 'device-address',
  CLASSES: 'classes',
  FREQUENCY_PLAN: 'frequency-plan',
  LORAWAN_VERSION: 'lorawan-version',
  JOIN_SERVER: 'join-server',
  JOIN_EUI: 'joineui',
  DEV_EUI: 'deveui',
  APP_KEY: 'appkey',
  NETWORK_KEY: 'network-key',
  APP_SESSION_KEY: 'application-session-key',
  REGIONAL_PARAMETERS: 'regional-parameters',
  NETWORK_SESSION_KEY: 'network-session-key',
  DATA_RATE_OFFSET: 'data-rate-offset',
  ACTIVATION_MODE: 'activation-mode',
  GATEWAY_ID: 'gateway-id',
  GATEWAY_EUI: 'gateway-eui',
  ENFORCE_DUTY_CYCLE: 'duty-cycle',
})
