
export default Object.freeze({
  C_ACTIVE_BLUE: '#3D73FF',
  C_ACTIVE_BLUE_HOVER: '#1E5DFF',
  C_ACTIVE_BLUE_ACTIVE: '#0047FF',
  C_ICON_FILL: '#686868',
  C_SUBTLE_FILL: '#AAAAAA',
  C_BACKDROP: '#F3F3F3',
  C_BACKDROP_LIGHTER: '#FAFAFA',
  C_TEXT_BACKDROP: '#ECECEC',
  TC_ACTIVE: '#3D73FF',
  TC_ACTIVE_HOVER: '#3D73FF',
  TC_ERROR: '#EA0000',
})
