package pubsub

import (
	"fmt"
	"regexp"
)

var uniqueIDPattern = regexp.MustCompile("(.*)\\:(.*)")

// PubSubUID generates an unique ID based on an application unique ID and a pub/sub ID.
func PubSubUID(appUID, id string) string {
	return fmt.Sprintf("%s:%s", appUID, id)
}

// SplitPubSubUID parses a unique ID generated by `ID` and returns the application unique ID and the pub/sub ID.
func SplitPubSubUID(uid string) (appUID string, id string) {
	matches := uniqueIDPattern.FindStringSubmatch(uid)
	if len(matches) != 3 {
		panic(fmt.Sprintf("invalid uniqueID `%s` with matches %v", uid, matches))
	}
	return matches[1], matches[2]
}
