package ttnmage

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/blang/semver"
	"github.com/magefile/mage/mg"
)

// Version namespace.
type Version mg.Namespace

var goVersionFile = `// Code generated by Makefile. DO NOT EDIT.

package version

// TTN Version
var TTN = "%s-dev"
`

const (
	goVersionFilePath = "pkg/version/ttn.go"
)

var packageJSONFilePaths = []string{"package.json", "sdk/js/package.json"}

// Files writes given version to files that contain version info
func (Version) Files() error {
	if mg.Verbose() {
		fmt.Println("Enter new version")
	}
	reader := bufio.NewReader(os.Stdin)
	version, err := reader.ReadString('\n')
	if err != nil {
		return err
	}
	version = strings.TrimPrefix(strings.TrimSpace(version), "v")
	_, err = semver.Parse(version)
	if err != nil {
		return err
	}
	err = os.WriteFile(goVersionFilePath, []byte(fmt.Sprintf(goVersionFile, version)), 0o644)
	if err != nil {
		return err
	}
	for _, packageJSONFile := range packageJSONFilePaths {
		if err = runYarn("run", "json",
			"-f", packageJSONFile,
			"-I",
			"-e", fmt.Sprintf(`this.version="%s"`, version),
		); err != nil {
			return err
		}
	}
	return nil
}
